export const SET_CURRENT_WEEK = "SET_CURRENT_WEEK";
export const SET_NEXT_WEEK = "SET_NEXT_WEEK";
export const SET_LOGGED_IN = "SET_LOGGED_IN";
export const SET_CONTENT_FIRST = "SET_CONTENT_FIRST";
export const SET_CONTENT_FIRST_NEXT = "SET_CONTENT_FIRST_NEXT";
export const SET_CONTENT_SECOND = "SET_CONTENT_SECOND";
export const SET_CONTENT_SECOND_NEXT = "SET_CONTENT_SECOND_NEXT";
